### ISSUE TITLE
"Please use <Provider store={...}>..." exception unable to track down root cause

### ISSUE THREAD

**Issue by rssfrncsrenishaw** [dai-shi/reactive-react-redux#34] opened 2019-08-07 12:57 UTC
I'm getting the following error after dispatching an action (this is dispatched using the standard dispatch from connect react-redux).

![image](https://user-images.githubusercontent.com/50481613/62624470-0aebec80-b91b-11e9-8dac-9c1f482269aa.png)

I'm currently only using reactive-react-redux in one component and have checked that I am not dispatching any reactive state.

I've wrapped my app inside of two providers, the normal react-redux one and the reactive-react-redux one. 

![image](https://user-images.githubusercontent.com/50481613/62624579-4edef180-b91b-11e9-8c99-615558dee387.png)

Any pointers?

**Comment by dai-shi** [comment] 2019-08-07 13:11
Hi, I created this example with Provider and ReactiveProvider.
https://codesandbox.io/s/reactive-react-redux-example-shpmn
It seems to work.

Could you provide an example to reproduce your issue?

**Comment by rssfrncs** [comment] 2019-09-12 07:00
Sorry I haven't been active on this thread (created using my corp account).

The branch where I was encountering this issue has since been abandoned, however I have used reactive-react-redux since and haven't encountered the issue. 

If I do encounter the same issue again I'll attempt to create a reproducible example.

**Comment by dai-shi** [comment] 2019-09-12 07:12
Thanks for the updates.

Let's close this issue then. Feel free to reopen it if you encounter the problem.

**Closed by dai-shi** 2019-09-12 07:12 UTC
